
name: run-lints
run-name: Linting for ${{ github.actor }}'s changes.
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pylint
        run: pip install pylint

      - name: Get changes to station_performance_pipeline
        id: changed-station_performance_pipeline
        uses: tj-actions/changed-files@v44
        with:
          files: |
             station_performance_pipeline/**.py

      - name: Run station_performance_pipeline linting if files changed
        if: steps.changed-station_performance_pipeline.outputs.any_changed == 'true'
        run: |
          pip install -r station_performance_pipeline/requirements.txt
          pylint station_performance_pipeline/*.py --ignore-patterns=test_ --fail-under=8.5

            - name: Get changes to station_performance_pipeline
        id: changed-station_performance_pipeline
        uses: tj-actions/changed-files@v44
        with:
          files: |
             station_performance_pipeline/**.py

      - name: Run incidents linting if files changed
        if: steps.changed-incidents.outputs.any_changed == 'true'
        run: |
          pip install -r incidents/requirements.txt
          pylint incidents/*.py --ignore-patterns=test_ --fail-under=8.5


