
name: run-lints
run-name: Linting for ${{ github.actor }}'s changes.
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pylint
        run: pip install pylint

      - name: Get changes to performance
        id: changed-performance
        uses: tj-actions/changed-files@v44
        with:
          files: |
             performance/**.py

      - name: Run performance linting if files changed
        if: steps.changed-performance.outputs.any_changed == 'true'
        run: |
          pip install -r performance/requirements.txt
          pylint performance/*.py --ignore-patterns=test_ --fail-under=8.5

      - name: Get changes to incidents
        id: changed-incidents
        uses: tj-actions/changed-files@v44
        with:
          files: |
             alerts/**.py

      - name: Run alerts linting if files changed
        if: steps.changed-alerts.outputs.any_changed == 'true'
        run: |
          pip install -r alerts/requirements.txt
          pylint alerts/*.py --ignore-patterns=test_ --fail-under=8.5


